# Generated by Django 5.1.4 on 2025-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_gymplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
