# Generated by Django 5.1.4 on 2025-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_memberprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
