# Generated by Django 5.1.4 on 2025-02-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_memberprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='account.gymplan'),
        ),
    ]
