# Generated by Django 5.1.4 on 2025-02-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_memberprofile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='plan',
        ),
        migrations.CreateModel(
            name='PlanAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='account.gymplan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
