# Generated by Django 5.1.4 on 2025-02-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_memberprofile_plan_planadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planadd',
            old_name='plan',
            new_name='planadded',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.gymplan'),
        ),
    ]
