# Generated by Django 5.1.4 on 2025-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_memberprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
