# Generated by Django 5.1.4 on 2025-02-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_memberprofile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='first_name',
        ),
    ]
